### ISSUE TITLE
MatchIt update to 4.0.0 build fails 

### ISSUE THREAD

**Issue by aniruhil** [kosukeimai/MatchIt#42]
I get the following error when updating from 3.0.2 to 4.0.0:

```
nnm.cpp:213:29: error: expected expression
                            [&match_distance](int k, int j) {return match_distance[k] < match_distance[j];});
                            ^
1 error generated.
make: *** [nnm.o] Error 1

```

Any clues or possible workarounds would be very welcome. 

SessionInfo() is given below in the details. 

<details>
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    yaml_2.2.1   

> install.packages("MatchIt")

  There is a binary version available but the source version is later:
        binary source needs_compilation
MatchIt  3.0.2  4.0.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) y
installing the source package ‘MatchIt’

trying URL 'https://cran.rstudio.com/src/contrib/MatchIt_4.0.0.tar.gz'
Content type 'application/x-gzip' length 1374846 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

* installing *source* package ‘MatchIt’ ...
** package ‘MatchIt’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c nnm.cpp -o nnm.o
nnm.cpp:213:29: error: expected expression
                            [&match_distance](int k, int j) {return match_distance[k] < match_distance[j];});
                            ^
1 error generated.
make: *** [nnm.o] Error 1
ERROR: compilation failed for package ‘MatchIt’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/MatchIt’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/MatchIt’
Warning in install.packages :
  installation of package ‘MatchIt’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/qh/6q39v0755_54rxmbl8m5ttnwy0twd7/T/RtmpcY8fRr/downloaded_packages’
```
</details>

**Comment by ngreifer** [comment]
Hi, thank you for pointing this out, and sorry for the inconvenience. I've fixed this on my version of `MatchIt` and will be merging it to this repository soon. You can install the fixed version using `devtools::install_github("ngreifer/MatchIt")` for now.

**Comment by ngreifer** [comment]
I just merged the two versions, so you should be able to install it from this repository as well (i.e., using `devtools::install_github("kosukeimai/MatchIt")`). I'll close this issue once the version on CRAN no longer has this problem.

**Comment by aniruhil** [comment]
Worked like a charm @ngreifer. Many thanks for the quick fix.
